//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actmis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEvents
    {
        public int fId { get; set; }
        public string fUserId { get; set; }
        public string fPId { get; set; }
        public string fName { get; set; }
        public Nullable<decimal> fPrice { get; set; }
        public string fImg { get; set; }
        public string fDescription { get; set; }
        public string fDate { get; set; }
        public string fType_no { get; set; }
        public string fArea { get; set; }
        public string fType_ca1 { get; set; }
        public string fType_ca2 { get; set; }
        public string fType_ca3 { get; set; }
        public string fPosition { get; set; }
        public string fHost { get; set; }
        public string fPeople { get; set; }
        public string fDes_detail { get; set; }
    }
}
